Recruitee:
  - recruitee
  - robovision
  - faktionbv1
  - legalfly
  - daltix
  - qollabi
Lever:
  - deliverect
  - silverfin
  - wandb
Workable:
  - novemberfive
  - sinch
  - boardofinnovation
  - mimica
#Personio:

Greenhouse:
  - showpad
  - assemblyai
  - algolia
# New section for the aggregator API


# We can remove or keep JSearch for now.
JSearch:
  - AI Engineer in Belgium

# Add the new Adzuna section with structured configs
Adzuna:
  - what: 'AI '
    where: 'Netherlands'
    country_code: 'nl'
  - what: 'Product Manager'
    where: 'Belgium'
    country_code: 'be'
  - what: 'AI'
    where: 'Belgium'
    country_code: 'be'

# Add the new, working scraper
"JOIN.com":
  - query: 'AI'
    country_code: 'BE' # Belgium
  - query: 'Product Manager'
    country_code: 'NL' # Netherlands
# In config/job_sources.yml
# ... (your other scraper sections)

# This is a query-based scraper, like Adzuna
WelcomeToTheJungle:
  - query: 'AI'
    location: 'belgium' # WTTJ uses lowercase location slugs
  - query: 'AI'
    location: 'netherlands'
  - query: 'Product'
    location: 'belgium'
