recruitee_companies:
  - recruitee
  - robovision
  - faktionbv1
  - legalfly
  - daltix
lever_companies:
  - deliverect
  - silverfin
workable_companies:
  - novemberfive
  - sinch
Personio:
  - mimi
  - wwf-belgium
  - stanley-stella
  - aeceuropes
  - technopolis-group
  - sensorfact
Greenhouse:
  - topcompare
  - dataroots
  - trustpilot
# New section for the aggregator API
JSearch:
  - AI Engineer in Belgium
  - Data Scientist in Belgium
  - Machine Learning, Antwerp
# ... your other scraper sections ...

# We can remove or keep JSearch for now.
JSearch:
  - AI Engineer in Belgium

# Add the new Adzuna section with structured configs
Adzuna:
  - what: 'AI Engineer'
    where: 'Belgium'
    country_code: 'be'
  - what: 'Data Scientist'
    where: 'Netherlands'
    country_code: 'nl'
  - what: 'Machine Learning'
    where: 'Antwerp'
    country_code: 'be'
